services:
  - type: web
    name: explorador-planetario-api
    env: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && cd server && npm install --legacy-peer-deps && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: DATABASE_URL
        value: mongodb+srv://probuho:MiBaseDeDatos42@gepddb.jz5tljo.mongodb.net/explorador-planetario
      - key: JWT_SECRET
        value: mi_secreto_super_seguro_2024
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: http://localhost:5173 